# Full image (all CLI tools installed):
#   $ docker compose -f docker-compose.yml -f docker-compose-full.yml up

services:
  spiderfoot:
    build:
      context: ./
      dockerfile: ./Dockerfile.full 
